name: Metrics
on:
  # Ejecutar automáticamente a medianoche
  schedule: [{cron: "0 0 * * *"}]
  # Ejecutar manualmente
  workflow_dispatch:
  # Ejecutar al hacer push
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          config_timezone: America/Mexico_City
          
          # DISEÑO 3D EXPANDIDO
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # HÁBITOS
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          
          # ESTRELLAS
          plugin_stars: yes
          plugin_stars_limit: 3
