name: Metrics
on:
  # Se actualiza cada 24 horas automÃ¡ticamente
  schedule: [{cron: "0 0 * * *"}]
  # O cuando lo pidas manualmente
  workflow_dispatch:
  # O cada vez que haces push en la rama master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Opciones de diseÃ±o (puedes cambiar esto luego)
          user: Carlos0567z
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_stars: yes
          plugin_habits: yes
          plugin_habits_charts: yes
