name: Metrics
on:
  # Se actualiza cada 24 horas autom√°ticamente
  schedule: [{cron: "0 0 * * *"}]
  # O cuando lo pidas manualmente
  workflow_dispatch:
  # O cada vez que haces push en la rama master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          # ESTILO 3D
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # LENGUAJES DETALLADOS
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
