name: Metrics
on:
  # Se actualiza cada 24 horas automáticamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se actualiza cada vez que subes cambios a la rama principal
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token secreto (NO BORRES ESTO)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Nombre del archivo que se generará
          filename: github-metrics.svg
          
          # Configuración General
          user: Carlos0567z
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          config_display: large
          
          # 1. Calendario 3D (Isométrico)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # 2. Lenguajes Detallados
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          # 3. Trofeos y Logros (Gamer)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
